import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { ClientWrapper } from "@/components/ClientWrapper";

// Main font
const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
// Display font for headers
const spaceGrotesk = Space_Grotesk({ subsets: ["latin"], variable: '--font-space' });

export const metadata: Metadata = {
  title: "My Portfolio | Fullstack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} ${spaceGrotesk.variable} bg-background text-foreground font-sans antialiased selection:bg-black selection:text-white dark:selection:bg-white dark:selection:text-black transition-colors duration-500`}>
        <ThemeProvider>
          <ClientWrapper>
            <main className="flex flex-col min-h-screen w-full relative">
              {children}
            </main>
          </ClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}